import type { RawLead } from "@/types/hunter";

// ============================================================
// Realistic Italian mock businesses — used when GOOGLE_PLACES_API_KEY is
// absent so the Hunter is fully functional offline. Mix of
// categories, cities, ratings, review counts, and website status.
// ============================================================

export const MOCK_HUNTER_LEADS: RawLead[] = [
  {
    id: "hunt-mi-01",
    name: "Salone Marco Acconciature",
    category: "parrucchiere",
    address: "Via Torino 45, Milano",
    phone: "02 8901 2345",
    rating: 4.7,
    reviews: 132,
    has_website: false,
    website: null,
  },
  {
    id: "hunt-mi-02",
    name: "Barber House Navigli",
    category: "barbiere",
    address: "Via Vigevano 12, Milano",
    phone: "02 5810 0099",
    rating: 4.9,
    reviews: 88,
    has_website: false,
    website: null,
  },
  {
    id: "hunt-mi-03",
    name: "Estetica Bellezza Pura",
    category: "estetista",
    address: "Corso Buenos Aires 78, Milano",
    phone: "02 2940 1122",
    rating: 4.5,
    reviews: 54,
    has_website: true,
    website: "https://esteticabellezzapura.it",
  },
  {
    id: "hunt-mi-04",
    name: "Inkwell Tattoo Studio",
    category: "tattoo studio",
    address: "Via Paolo Sarpi 30, Milano",
    phone: "02 3653 7788",
    rating: 4.8,
    reviews: 210,
    has_website: false,
    website: null,
  },
  {
    id: "hunt-rm-01",
    name: "Trattoria da Nonna Lina",
    category: "trattoria",
    address: "Via dei Coronari 22, Roma",
    phone: "06 6880 4567",
    rating: 4.6,
    reviews: 178,
    has_website: false,
    website: null,
  },
  {
    id: "hunt-rm-02",
    name: "Pizzeria Sant'Antonio",
    category: "pizzeria",
    address: "Via Ostiense 110, Roma",
    phone: "06 5743 2210",
    rating: 4.4,
    reviews: 96,
    has_website: true,
    website: "https://pizzeriasantantonio.com",
  },
  {
    id: "hunt-rm-03",
    name: "Fitness Lab Roma",
    category: "palestra",
    address: "Viale Marconi 55, Roma",
    phone: "06 5530 9988",
    rating: 4.3,
    reviews: 64,
    has_website: false,
    website: null,
  },
  {
    id: "hunt-rm-04",
    name: "Hair Couture Prati",
    category: "parrucchiere",
    address: "Via Cola di Rienzo 145, Roma",
    phone: "06 3211 6677",
    rating: 4.8,
    reviews: 121,
    has_website: false,
    website: null,
  },
  {
    id: "hunt-to-01",
    name: "Caffè del Centro",
    category: "bar",
    address: "Via Po 18, Torino",
    phone: "011 812 3344",
    rating: 4.5,
    reviews: 73,
    has_website: false,
    website: null,
  },
  {
    id: "hunt-to-02",
    name: "Studio Estetico Aura",
    category: "estetista",
    address: "Corso Vittorio Emanuele 90, Torino",
    phone: "011 545 6611",
    rating: 4.7,
    reviews: 41,
    has_website: false,
    website: null,
  },
  {
    id: "hunt-na-01",
    name: "Pizzeria Mare Blu",
    category: "pizzeria",
    address: "Via Partenope 9, Napoli",
    phone: "081 764 5522",
    rating: 4.9,
    reviews: 256,
    has_website: true,
    website: "https://pizzeriamareblu.it",
  },
  {
    id: "hunt-na-02",
    name: "Barbieri Spaccanapoli",
    category: "barbiere",
    address: "Via Toledo 200, Napoli",
    phone: "081 552 8833",
    rating: 4.6,
    reviews: 110,
    has_website: false,
    website: null,
  },
  {
    id: "hunt-bo-01",
    name: "Osteria del Portico",
    category: "ristorante",
    address: "Via Zamboni 16, Bologna",
    phone: "051 226 7788",
    rating: 4.7,
    reviews: 142,
    has_website: false,
    website: null,
  },
  {
    id: "hunt-bo-02",
    name: "Glamour Nails & Beauty",
    category: "estetista",
    address: "Via Indipendenza 40, Bologna",
    phone: "051 234 9900",
    rating: 4.2,
    reviews: 28,
    has_website: false,
    website: null,
  },
];
