import type { Interaction, Lead, MindEdge } from "@/types";

// ============================================================
// AYRO SPECTRE — demo dataset (used when Turso is not set,
// and mirrored 1:1 in lib/turso/schema.sql).
// Invented but plausible Italian SMB / hospitality / ADM leads.
// ============================================================

const now = Date.now();
const ago = (days: number, hours = 0): string =>
  new Date(now - days * 86_400_000 - hours * 3_600_000).toISOString();

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-01",
    name: "Giorgia Memmola",
    company: "Estetica Luce di Luna",
    email: "info@lucedilunaestetica.it",
    phone: "+39 080 555 0101",
    source: "maps",
    status: "warm",
    value: 4800,
    probability: 55,
    last_contact: ago(3),
    next_action: "Inviare demo AyroDesk24 (Sara) via WhatsApp",
    notes: "Centro estetico Bari, 3 cabine. Perde prenotazioni la sera.",
    tags: ["beauty", "ayrodesk24", "bari"],
    created_at: ago(20),
    updated_at: ago(3),
    graph_connections: ["lead-07", "lead-17"],
  },
  {
    id: "lead-02",
    name: "Vito Sannicandro",
    company: "Barber House Tridente",
    email: "tridente.barber@gmail.com",
    phone: "+39 080 555 0102",
    source: "referral",
    status: "hot",
    value: 3600,
    probability: 72,
    last_contact: ago(1),
    next_action: "Chiudere setup €99 + Studio €129/mese",
    notes: "Modugno. 2 poltrone, no-show frequenti. Vuole reminder automatici.",
    tags: ["barber", "ayrodesk24"],
    created_at: ago(14),
    updated_at: ago(1),
    graph_connections: ["lead-12"],
  },
  {
    id: "lead-03",
    name: "Anna De Santis",
    company: "B&B Corte dei Mercanti",
    email: "prenotazioni@cortedeimercanti.it",
    phone: "+39 080 555 0103",
    source: "maps",
    status: "proposal",
    value: 7200,
    probability: 64,
    last_contact: ago(2),
    next_action: "Follow-up su proposta AyroStay Pro",
    notes: "Polignano. 6 camere. Risponde tardi su Booking, vuole H24.",
    tags: ["hospitality", "ayrostay", "puglia"],
    created_at: ago(25),
    updated_at: ago(2),
    graph_connections: ["lead-08", "lead-15"],
  },
  {
    id: "lead-04",
    name: "Cosimo Lacirignola",
    company: "Ristorante Sale & Mare",
    email: "info@salemare.it",
    phone: "+39 080 555 0104",
    source: "cold",
    status: "warm",
    value: 5400,
    probability: 48,
    last_contact: ago(9),
    next_action: "Ricontattare: gestione prenotazioni tavoli + recensioni",
    notes: "Monopoli. Estate sold-out, vuole automazione liste d'attesa.",
    tags: ["restaurant", "automazione"],
    created_at: ago(30),
    updated_at: ago(9),
    graph_connections: ["lead-10"],
  },
  {
    id: "lead-05",
    name: "Daniele Sforza",
    company: "Poker Club Apex",
    email: "direzione@apexcardroom.it",
    phone: "+39 080 555 0105",
    source: "referral",
    status: "negotiation",
    value: 36000,
    probability: 68,
    last_contact: ago(2),
    next_action: "Definire pricing Reactivation OS (Silver 3-4 mesi)",
    notes: "Card room Bari. Interessato a voice+WA reactivation giocatori dormienti.",
    tags: ["adm", "poker", "reactivation-os", "high-value"],
    created_at: ago(40),
    updated_at: ago(2),
    graph_connections: ["lead-19", "lead-14", "lead-09"],
  },
  {
    id: "lead-06",
    name: "Dott. Marco Ferrara",
    company: "Studio Dentistico Ferrara",
    email: "segreteria@studioferrara.it",
    phone: "+39 080 555 0106",
    source: "linkedin",
    status: "cold",
    value: 6000,
    probability: 22,
    last_contact: ago(16),
    next_action: "Primo contatto: triage chiamate + richiami appuntamenti",
    notes: "Bari. Segretaria oberata, molte chiamate perse a pranzo.",
    tags: ["studio", "ayrodesk24"],
    created_at: ago(18),
    updated_at: ago(16),
    graph_connections: ["lead-13"],
  },
  {
    id: "lead-07",
    name: "Federica Carbonara",
    company: "Nails & Co",
    email: "nailsandco.bitonto@gmail.com",
    phone: "+39 080 555 0107",
    source: "maps",
    status: "warm",
    value: 3000,
    probability: 51,
    last_contact: ago(4),
    next_action: "Mandare case study Glam Beauty",
    notes: "Bitonto. Solo Instagram DM, vuole prenotazioni da social.",
    tags: ["beauty", "ayrodesk24", "social-booking"],
    created_at: ago(12),
    updated_at: ago(4),
    graph_connections: ["lead-01"],
  },
  {
    id: "lead-08",
    name: "Riccardo Pinto",
    company: "Hotel Maestrale",
    email: "info@hotelmaestrale.it",
    phone: "+39 0884 555 010",
    source: "referral",
    status: "hot",
    value: 12500,
    probability: 70,
    last_contact: ago(1),
    next_action: "Demo AyroStay Corporate + voice AI",
    notes: "Vieste, 28 camere. Stagionale, picco richieste estive ingestibile.",
    tags: ["hospitality", "ayrostay", "high-value"],
    created_at: ago(22),
    updated_at: ago(1),
    graph_connections: ["lead-03", "lead-15"],
  },
  {
    id: "lead-09",
    name: "Massimo Centonze",
    company: "Betwin Point Lecce",
    email: "m.centonze@betwinpoint.it",
    phone: "+39 0832 555 010",
    source: "referral",
    status: "proposal",
    value: 28000,
    probability: 58,
    last_contact: ago(6),
    next_action: "Inviare proposta Reactivation OS annuale",
    notes: "Concessionario ADM. Punto vendita + online, vuole retention.",
    tags: ["adm", "reactivation-os", "high-value"],
    created_at: ago(35),
    updated_at: ago(6),
    graph_connections: ["lead-14", "lead-05"],
  },
  {
    id: "lead-10",
    name: "Nico Lorusso",
    company: "Pizzeria Fornace 900",
    email: "fornace900@gmail.com",
    phone: "+39 080 555 0110",
    source: "maps",
    status: "closed",
    value: 2400,
    probability: 100,
    last_contact: ago(5),
    next_action: "Onboarding completato — upsell recensioni a 30gg",
    notes: "Bari. Cliente attivo AyroDesk24. Ottima referenza.",
    tags: ["restaurant", "ayrodesk24", "cliente"],
    created_at: ago(50),
    updated_at: ago(5),
    graph_connections: ["lead-04"],
  },
  {
    id: "lead-11",
    name: "Serena Quaranta",
    company: "Centro Estetico Aura",
    email: "aura.estetica@gmail.com",
    phone: "+39 099 555 0111",
    source: "cold",
    status: "cold",
    value: 3600,
    probability: 18,
    last_contact: ago(21),
    next_action: "Sequenza cold: prima email mai aperta, ritentare WA",
    notes: "Taranto. Non ha risposto al primo contatto.",
    tags: ["beauty", "cold"],
    created_at: ago(21),
    updated_at: ago(21),
    graph_connections: [],
  },
  {
    id: "lead-12",
    name: "Antonio Greco",
    company: "Barbershop King's",
    email: "kingsbarber.br@gmail.com",
    phone: "+39 0831 555 010",
    source: "maps",
    status: "warm",
    value: 3000,
    probability: 44,
    last_contact: ago(8),
    next_action: "Ricontattare dopo ferie: demo no-show reminder",
    notes: "Brindisi. Competitor diretto di Barber House Tridente.",
    tags: ["barber", "ayrodesk24"],
    created_at: ago(17),
    updated_at: ago(8),
    graph_connections: ["lead-02"],
  },
  {
    id: "lead-13",
    name: "Avv. Elena Marzano",
    company: "Studio Legale Marzano",
    email: "studio@avvmarzano.it",
    phone: "+39 080 555 0113",
    source: "linkedin",
    status: "warm",
    value: 5400,
    probability: 46,
    last_contact: ago(5),
    next_action: "Inviare info su filtro chiamate + smistamento pratiche",
    notes: "Bari. Vuole filtrare le chiamate non qualificate.",
    tags: ["studio", "ayrodesk24"],
    created_at: ago(19),
    updated_at: ago(5),
    graph_connections: ["lead-06"],
  },
  {
    id: "lead-14",
    name: "Pierluigi Faro",
    company: "Gaming Hall Royal",
    email: "p.faro@royalgaming.it",
    phone: "+39 0881 555 010",
    source: "referral",
    status: "hot",
    value: 31000,
    probability: 66,
    last_contact: ago(1),
    next_action: "Call tecnica integrazione DB giocatori",
    notes: "Foggia. Sala ADM, alta affluenza, churn giocatori alto.",
    tags: ["adm", "reactivation-os", "high-value"],
    created_at: ago(28),
    updated_at: ago(1),
    graph_connections: ["lead-05", "lead-09"],
  },
  {
    id: "lead-15",
    name: "Chiara Vetrugno",
    company: "Resort Cala Verde",
    email: "booking@calaverde.it",
    phone: "+39 0833 555 010",
    source: "maps",
    status: "negotiation",
    value: 16500,
    probability: 62,
    last_contact: ago(3),
    next_action: "Negoziare bundle AyroStay + voice per ristorante interno",
    notes: "Gallipoli. Resort + ristorante. Vuole un'unica AI per entrambi.",
    tags: ["hospitality", "ayrostay", "high-value"],
    created_at: ago(33),
    updated_at: ago(3),
    graph_connections: ["lead-08", "lead-03"],
  },
  {
    id: "lead-16",
    name: "Tommaso Conte",
    company: "Osteria del Borgo",
    email: "osteriadelborgo@gmail.com",
    phone: "+39 080 555 0116",
    source: "cold",
    status: "lost",
    value: 2800,
    probability: 0,
    last_contact: ago(27),
    next_action: "Perso: budget assente. Rivalutare in autunno.",
    notes: "Alberobello. Ha scelto un gestionale gratuito.",
    tags: ["restaurant", "lost"],
    created_at: ago(45),
    updated_at: ago(27),
    graph_connections: ["lead-20"],
  },
  {
    id: "lead-17",
    name: "Martina Lopez",
    company: "Beauty Lab Eden",
    email: "beautylabeden@gmail.com",
    phone: "+39 080 555 0117",
    source: "referral",
    status: "proposal",
    value: 4200,
    probability: 60,
    last_contact: ago(2),
    next_action: "Proposta Studio inviata, attendere risposta",
    notes: "Bari. 4 operatrici, agenda piena, vuole gestione liste.",
    tags: ["beauty", "ayrodesk24"],
    created_at: ago(15),
    updated_at: ago(2),
    graph_connections: ["lead-01"],
  },
  {
    id: "lead-18",
    name: "Dott. Luca Tedone",
    company: "Fisioterapia Movimento",
    email: "info@fisiomovimento.it",
    phone: "+39 0883 555 010",
    source: "linkedin",
    status: "cold",
    value: 4800,
    probability: 20,
    last_contact: ago(13),
    next_action: "Primo contatto: gestione richiami pazienti",
    notes: "Andria. Cicli di terapie, molti pazienti da richiamare.",
    tags: ["studio", "ayrodesk24"],
    created_at: ago(13),
    updated_at: ago(13),
    graph_connections: [],
  },
  {
    id: "lead-19",
    name: "Gennaro Esposito",
    company: "Poker Room Vesuvio",
    email: "g.esposito@vesuviopoker.it",
    phone: "+39 081 555 0119",
    source: "referral",
    status: "warm",
    value: 24000,
    probability: 40,
    last_contact: ago(7),
    next_action: "Inviare case study reactivation + ROI calculator",
    notes: "Napoli. Card room, competitor di Apex. Curioso ma cauto.",
    tags: ["adm", "poker", "reactivation-os", "high-value"],
    created_at: ago(24),
    updated_at: ago(7),
    graph_connections: ["lead-05"],
  },
  {
    id: "lead-20",
    name: "Ilaria Surano",
    company: "Caffè Letterario Pessoa",
    email: "pessoacaffe@gmail.com",
    phone: "+39 0832 555 020",
    source: "referral",
    status: "hot",
    value: 3200,
    probability: 74,
    last_contact: ago(1),
    next_action: "Chiudere: gestione eventi + prenotazioni serate",
    notes: "Lecce. Caffè con eventi serali. Referral da Osteria del Borgo.",
    tags: ["restaurant", "cafe", "automazione"],
    created_at: ago(10),
    updated_at: ago(1),
    graph_connections: ["lead-16"],
  },
];

export const MOCK_INTERACTIONS: Interaction[] = [
  {
    id: "int-01",
    lead_id: "lead-05",
    type: "meeting",
    content:
      "Incontro in sala. Sforza interessato alla reactivation dei giocatori inattivi da 90gg. Chiede numeri concreti di ROI.",
    sentiment: "positive",
    ai_summary: "Alto interesse, blocco su prova ROI. Inviare case study.",
    created_at: ago(2),
  },
  {
    id: "int-02",
    lead_id: "lead-05",
    type: "call",
    content:
      "Prima call esplorativa. Budget ampio ma vuole capire la compliance ADM.",
    sentiment: "neutral",
    ai_summary: "Obiezione compliance. Preparare scheda conformità ADM.",
    created_at: ago(9),
  },
  {
    id: "int-03",
    lead_id: "lead-08",
    type: "whatsapp",
    content:
      "Pinto: 'In agosto è impossibile rispondere a tutti, perdiamo prenotazioni dirette'. Apertura forte.",
    sentiment: "positive",
    ai_summary: "Pain stagionale chiaro. Spingere su prenotazioni dirette H24.",
    created_at: ago(1),
  },
  {
    id: "int-04",
    lead_id: "lead-03",
    type: "email",
    content: "Inviata proposta AyroStay Pro. Aperta 2 volte, nessuna risposta.",
    sentiment: "neutral",
    ai_summary: "Interesse tiepido. Follow-up con scarcity entro 48h.",
    created_at: ago(2),
  },
  {
    id: "int-05",
    lead_id: "lead-02",
    type: "call",
    content:
      "Sannicandro pronto a partire. Chiede solo se l'AI gestisce le modifiche last-minute.",
    sentiment: "positive",
    ai_summary: "Pronto a chiudere. Rispondere su reschedule automatico.",
    created_at: ago(1),
  },
  {
    id: "int-06",
    lead_id: "lead-16",
    type: "note",
    content: "Ha scelto un gestionale gratuito. Nessun budget al momento.",
    sentiment: "negative",
    ai_summary: "Perso per prezzo. Nurturing trimestrale.",
    created_at: ago(27),
  },
  {
    id: "int-07",
    lead_id: "lead-14",
    type: "call",
    content:
      "Faro chiede integrazione col loro DB giocatori esistente. Aspetto tecnico chiave.",
    sentiment: "positive",
    ai_summary: "Deal tecnico-dipendente. Coinvolgere parte dev su integrazione DB.",
    created_at: ago(1),
  },
  {
    id: "int-08",
    lead_id: "lead-20",
    type: "whatsapp",
    content: "Surano entusiasta, vuole partire prima del prossimo evento.",
    sentiment: "positive",
    ai_summary: "Urgenza naturale (evento). Chiudere subito.",
    created_at: ago(1),
  },
];

export const MOCK_MIND_EDGES: MindEdge[] = [
  {
    id: "edge-01",
    source_id: "lead-05",
    target_id: "lead-19",
    relation_type: "competitor",
    strength: 8,
    evidence: "Due card room rivali sullo stesso circuito tornei Sud Italia.",
  },
  {
    id: "edge-02",
    source_id: "lead-05",
    target_id: "lead-14",
    relation_type: "colleague",
    strength: 6,
    evidence: "Entrambi concessionari ADM, contatti allo stesso evento di settore.",
  },
  {
    id: "edge-03",
    source_id: "lead-09",
    target_id: "lead-14",
    relation_type: "competitor",
    strength: 7,
    evidence: "Punti vendita ADM in province limitrofe (Lecce/Foggia).",
  },
  {
    id: "edge-04",
    source_id: "lead-02",
    target_id: "lead-12",
    relation_type: "competitor",
    strength: 5,
    evidence: "Due barbershop con clientela sovrapposta tra Modugno e Brindisi.",
  },
  {
    id: "edge-05",
    source_id: "lead-01",
    target_id: "lead-07",
    relation_type: "colleague",
    strength: 6,
    evidence: "Si seguono su Instagram, condividono fornitore prodotti.",
  },
  {
    id: "edge-06",
    source_id: "lead-01",
    target_id: "lead-17",
    relation_type: "friend",
    strength: 7,
    evidence: "Stesso corso di formazione estetica nel 2023.",
  },
  {
    id: "edge-07",
    source_id: "lead-03",
    target_id: "lead-08",
    relation_type: "colleague",
    strength: 5,
    evidence: "Strutture ricettive pugliesi, stesso consorzio turistico.",
  },
  {
    id: "edge-08",
    source_id: "lead-08",
    target_id: "lead-15",
    relation_type: "colleague",
    strength: 6,
    evidence: "Entrambi nel circuito resort del Salento/Gargano.",
  },
  {
    id: "edge-09",
    source_id: "lead-04",
    target_id: "lead-10",
    relation_type: "competitor",
    strength: 4,
    evidence: "Ristorazione Bari area, clientela simile.",
  },
  {
    id: "edge-10",
    source_id: "lead-06",
    target_id: "lead-13",
    relation_type: "friend",
    strength: 5,
    evidence: "Studi professionali nello stesso palazzo a Bari.",
  },
  {
    id: "edge-11",
    source_id: "lead-16",
    target_id: "lead-20",
    relation_type: "colleague",
    strength: 6,
    evidence: "Surano (Pessoa) arrivata come referral diretto dall'Osteria del Borgo.",
  },
  {
    id: "edge-12",
    source_id: "lead-05",
    target_id: "lead-09",
    relation_type: "colleague",
    strength: 5,
    evidence: "Contatti incrociati nel mondo ADM, possibile introduzione.",
  },
];
